import { SystemCategory } from 'shared-types'

import { PlaidCategory } from '../types/PlaidCategory'

export const mapCategory = (category: PlaidCategory) => {
  switch (category) {
    case 'INCOME_DIVIDENDS':
      return SystemCategory.Dividends
    case 'INCOME_INTEREST_EARNED':
      return SystemCategory.InterestEarned
    case 'INCOME_RETIREMENT_PENSION':
      return SystemCategory.RetirementPension
    case 'INCOME_TAX_REFUND':
      return SystemCategory.TaxRefund
    case 'INCOME_UNEMPLOYMENT':
      return SystemCategory.Unemployment
    case 'INCOME_WAGES':
      return SystemCategory.Wages
    case 'INCOME_OTHER_INCOME':
      return SystemCategory.OtherIncome
    case 'TRANSFER_IN_CASH_ADVANCES_AND_LOANS':
      return SystemCategory.CashAdvancesAndLoans
    case 'TRANSFER_IN_DEPOSIT':
      return SystemCategory.Deposit
    case 'TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS':
      return SystemCategory.InvestmentAndRetirementFunds
    case 'TRANSFER_IN_SAVINGS':
      return SystemCategory.Savings
    case 'TRANSFER_IN_ACCOUNT_TRANSFER':
      return SystemCategory.AccountTransfer
    case 'TRANSFER_IN_OTHER_TRANSFER_IN':
      return SystemCategory.OtherTransferIn
    case 'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS':
      return SystemCategory.InvestmentAndRetirementFunds
    case 'TRANSFER_OUT_SAVINGS':
      return SystemCategory.Savings
    case 'TRANSFER_OUT_WITHDRAWAL':
      return SystemCategory.Withdrawal
    case 'TRANSFER_OUT_ACCOUNT_TRANSFER':
      return SystemCategory.AccountTransfer
    case 'TRANSFER_OUT_OTHER_TRANSFER_OUT':
      return SystemCategory.OtherTransferOut
    case 'LOAN_PAYMENTS_CAR_PAYMENT':
      return SystemCategory.CarPayment
    case 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT':
      return SystemCategory.CreditCardPayment
    case 'LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT':
      return SystemCategory.PersonalLoanPayment
    case 'LOAN_PAYMENTS_MORTGAGE_PAYMENT':
      return SystemCategory.MortgagePayment
    case 'LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT':
      return SystemCategory.StudentLoanPayment
    case 'LOAN_PAYMENTS_OTHER_PAYMENT':
      return SystemCategory.OtherPayment
    case 'BANK_FEES_ATM_FEES':
      return SystemCategory.AtmFees
    case 'BANK_FEES_FOREIGN_TRANSACTION_FEES':
      return SystemCategory.ForeignTransactionFees
    case 'BANK_FEES_INSUFFICIENT_FUNDS':
      return SystemCategory.InsufficientFunds
    case 'BANK_FEES_INTEREST_CHARGE':
      return SystemCategory.InterestCharge
    case 'BANK_FEES_OVERDRAFT_FEES':
      return SystemCategory.OverdraftFees
    case 'BANK_FEES_OTHER_BANK_FEES':
      return SystemCategory.OtherBankFees
    case 'ENTERTAINMENT_CASINOS_AND_GAMBLING':
      return SystemCategory.CasinosAndGambling
    case 'ENTERTAINMENT_MUSIC_AND_AUDIO':
      return SystemCategory.MusicAndAudio
    case 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS':
      return SystemCategory.SportingEventsAmusementParksAndMuseums
    case 'ENTERTAINMENT_TV_AND_MOVIES':
      return SystemCategory.TvAndMovies
    case 'ENTERTAINMENT_VIDEO_GAMES':
      return SystemCategory.VideoGames
    case 'ENTERTAINMENT_OTHER_ENTERTAINMENT':
      return SystemCategory.OtherEntertainment
    case 'FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR':
      return SystemCategory.BeerWineAndLiquor
    case 'FOOD_AND_DRINK_COFFEE':
      return SystemCategory.Coffee
    case 'FOOD_AND_DRINK_FAST_FOOD':
      return SystemCategory.FastFood
    case 'FOOD_AND_DRINK_GROCERIES':
      return SystemCategory.Groceries
    case 'FOOD_AND_DRINK_RESTAURANT':
      return SystemCategory.Restaurant
    case 'FOOD_AND_DRINK_VENDING_MACHINES':
      return SystemCategory.VendingMachines
    case 'FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK':
      return SystemCategory.OtherFoodAndDrink
    case 'GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS':
      return SystemCategory.BookstoresAndNewsstands
    case 'GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES':
      return SystemCategory.ClothingAndAccessories
    case 'GENERAL_MERCHANDISE_CONVENIENCE_STORES':
      return SystemCategory.ConvenienceStores
    case 'GENERAL_MERCHANDISE_DEPARTMENT_STORES':
      return SystemCategory.DepartmentStores
    case 'GENERAL_MERCHANDISE_DISCOUNT_STORES':
      return SystemCategory.DiscountStores
    case 'GENERAL_MERCHANDISE_ELECTRONICS':
      return SystemCategory.Electronics
    case 'GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES':
      return SystemCategory.GiftsAndNovelties
    case 'GENERAL_MERCHANDISE_OFFICE_SUPPLIES':
      return SystemCategory.OfficeSupplies
    case 'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES':
      return SystemCategory.OnlineMarketplaces
    case 'GENERAL_MERCHANDISE_PET_SUPPLIES':
      return SystemCategory.PetSupplies
    case 'GENERAL_MERCHANDISE_SPORTING_GOODS':
      return SystemCategory.SportingGoods
    case 'GENERAL_MERCHANDISE_SUPERSTORES':
      return SystemCategory.Superstores
    case 'GENERAL_MERCHANDISE_TOBACCO_AND_VAPE':
      return SystemCategory.TobaccoAndVape
    case 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE':
      return SystemCategory.OtherGeneralMerchandise
    case 'HOME_IMPROVEMENT_FURNITURE':
      return SystemCategory.Furniture
    case 'HOME_IMPROVEMENT_HARDWARE':
      return SystemCategory.Hardware
    case 'HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE':
      return SystemCategory.RepairAndMaintenance
    case 'HOME_IMPROVEMENT_SECURITY':
      return SystemCategory.Security
    case 'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT':
      return SystemCategory.OtherHomeImprovement
    case 'MEDICAL_DENTAL_CARE':
      return SystemCategory.DentalCare
    case 'MEDICAL_EYE_CARE':
      return SystemCategory.EyeCare
    case 'MEDICAL_NURSING_CARE':
      return SystemCategory.NursingCare
    case 'MEDICAL_PHARMACIES_AND_SUPPLEMENTS':
      return SystemCategory.PharmaciesAndSupplements
    case 'MEDICAL_PRIMARY_CARE':
      return SystemCategory.PrimaryCare
    case 'MEDICAL_VETERINARY_SERVICES':
      return SystemCategory.VeterinaryServices
    case 'MEDICAL_OTHER_MEDICAL':
      return SystemCategory.OtherMedical
    case 'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS':
      return SystemCategory.GymsAndFitnessCenters
    case 'PERSONAL_CARE_HAIR_AND_BEAUTY':
      return SystemCategory.HairAndBeauty
    case 'PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING':
      return SystemCategory.LaundryAndDryCleaning
    case 'PERSONAL_CARE_OTHER_PERSONAL_CARE':
      return SystemCategory.OtherPersonalCare
    case 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING':
      return SystemCategory.AccountingAndFinancialPlanning
    case 'GENERAL_SERVICES_AUTOMOTIVE':
      return SystemCategory.Automotive
    case 'GENERAL_SERVICES_CHILDCARE':
      return SystemCategory.Childcare
    case 'GENERAL_SERVICES_CONSULTING_AND_LEGAL':
      return SystemCategory.ConsultingAndLegal
    case 'GENERAL_SERVICES_EDUCATION':
      return SystemCategory.Education
    case 'GENERAL_SERVICES_INSURANCE':
      return SystemCategory.Insurance
    case 'GENERAL_SERVICES_POSTAGE_AND_SHIPPING':
      return SystemCategory.PostageAndShipping
    case 'GENERAL_SERVICES_STORAGE':
      return SystemCategory.Storage
    case 'GENERAL_SERVICES_OTHER_GENERAL_SERVICES':
      return SystemCategory.OtherGeneralServices
    case 'GOVERNMENT_AND_NON_PROFIT_DONATIONS':
      return SystemCategory.Donations
    case 'GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES':
      return SystemCategory.GovernmentDepartmentsAndAgencies
    case 'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT':
      return SystemCategory.TaxPayment
    case 'GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT':
      return SystemCategory.OtherGovernmentAndNonProfit
    case 'TRANSPORTATION_BIKES_AND_SCOOTERS':
      return SystemCategory.BikesAndScooters
    case 'TRANSPORTATION_GAS':
      return SystemCategory.Gas
    case 'TRANSPORTATION_PARKING':
      return SystemCategory.Parking
    case 'TRANSPORTATION_PUBLIC_TRANSIT':
      return SystemCategory.PublicTransit
    case 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES':
      return SystemCategory.TaxisAndRideShares
    case 'TRANSPORTATION_TOLLS':
      return SystemCategory.Tolls
    case 'TRANSPORTATION_OTHER_TRANSPORTATION':
      return SystemCategory.OtherTransportation
    case 'TRAVEL_FLIGHTS':
      return SystemCategory.Flights
    case 'TRAVEL_LODGING':
      return SystemCategory.Lodging
    case 'TRAVEL_RENTAL_CARS':
      return SystemCategory.RentalCars
    case 'TRAVEL_OTHER_TRAVEL':
      return SystemCategory.OtherTravel
    case 'RENT_AND_UTILITIES_GAS_AND_ELECTRICITY':
      return SystemCategory.GasAndElectricity
    case 'RENT_AND_UTILITIES_INTERNET_AND_CABLE':
      return SystemCategory.InternetAndCable
    case 'RENT_AND_UTILITIES_RENT':
      return SystemCategory.Rent
    case 'RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT':
      return SystemCategory.SewageAndWasteManagement
    case 'RENT_AND_UTILITIES_TELEPHONE':
      return SystemCategory.Telephone
    case 'RENT_AND_UTILITIES_WATER':
      return SystemCategory.Water
    case 'RENT_AND_UTILITIES_OTHER_UTILITIES':
      return SystemCategory.OtherUtilities
    default:
      return SystemCategory.Miscellaneous
  }
}
