import { AccountSubtype as PlaidAccountSubType } from 'plaid'
import { AccountSubType } from 'shared-types'

export const mapPlaidAccountSubType = (accountSubType: PlaidAccountSubType | null) => {
  switch (accountSubType) {
    case PlaidAccountSubType._401a:
      return AccountSubType._401a
    case PlaidAccountSubType._401k:
      return AccountSubType._401k
    case PlaidAccountSubType._403B:
      return AccountSubType._403B
    case PlaidAccountSubType._457b:
      return AccountSubType._457b
    case PlaidAccountSubType._529:
      return AccountSubType._529
    case PlaidAccountSubType.Brokerage:
      return AccountSubType.Brokerage
    case PlaidAccountSubType.CashIsa:
      return AccountSubType.CashIsa
    case PlaidAccountSubType.CryptoExchange:
      return AccountSubType.CryptoExchange
    case PlaidAccountSubType.EducationSavingsAccount:
      return AccountSubType.EducationSavingsAccount
    case PlaidAccountSubType.Ebt:
      return AccountSubType.Ebt
    case PlaidAccountSubType.FixedAnnuity:
      return AccountSubType.FixedAnnuity
    case PlaidAccountSubType.Gic:
      return AccountSubType.Gic
    case PlaidAccountSubType.HealthReimbursementArrangement:
      return AccountSubType.HealthReimbursementArrangement
    case PlaidAccountSubType.Hsa:
      return AccountSubType.Hsa
    case PlaidAccountSubType.Isa:
      return AccountSubType.Isa
    case PlaidAccountSubType.Ira:
      return AccountSubType.Ira
    case PlaidAccountSubType.Lif:
      return AccountSubType.Lif
    case PlaidAccountSubType.LifeInsurance:
      return AccountSubType.LifeInsurance
    case PlaidAccountSubType.Lira:
      return AccountSubType.Lira
    case PlaidAccountSubType.Lrif:
      return AccountSubType.Lrif
    case PlaidAccountSubType.Lrsp:
      return AccountSubType.Lrsp
    case PlaidAccountSubType.NonCustodialWallet:
      return AccountSubType.NonCustodialWallet
    case PlaidAccountSubType.NonTaxableBrokerageAccount:
      return AccountSubType.NonTaxableBrokerageAccount
    case PlaidAccountSubType.OtherInsurance:
      return AccountSubType.OtherInsurance
    case PlaidAccountSubType.OtherAnnuity:
      return AccountSubType.OtherAnnuity
    case PlaidAccountSubType.Prif:
      return AccountSubType.Prif
    case PlaidAccountSubType.Rdsp:
      return AccountSubType.Rdsp
    case PlaidAccountSubType.Resp:
      return AccountSubType.Resp
    case PlaidAccountSubType.Rlif:
      return AccountSubType.Rlif
    case PlaidAccountSubType.Rrif:
      return AccountSubType.Rrif
    case PlaidAccountSubType.Pension:
      return AccountSubType.Pension
    case PlaidAccountSubType.ProfitSharingPlan:
      return AccountSubType.ProfitSharingPlan
    case PlaidAccountSubType.Retirement:
      return AccountSubType.Retirement
    case PlaidAccountSubType.Roth:
      return AccountSubType.Roth
    case PlaidAccountSubType.Roth401k:
      return AccountSubType.Roth401k
    case PlaidAccountSubType.Rrsp:
      return AccountSubType.Rrsp
    case PlaidAccountSubType.SepIra:
      return AccountSubType.SepIra
    case PlaidAccountSubType.SimpleIra:
      return AccountSubType.SimpleIra
    case PlaidAccountSubType.Sipp:
      return AccountSubType.Sipp
    case PlaidAccountSubType.StockPlan:
      return AccountSubType.StockPlan
    case PlaidAccountSubType.ThriftSavingsPlan:
      return AccountSubType.ThriftSavingsPlan
    case PlaidAccountSubType.Tfsa:
      return AccountSubType.Tfsa
    case PlaidAccountSubType.Trust:
      return AccountSubType.Trust
    case PlaidAccountSubType.Ugma:
      return AccountSubType.Ugma
    case PlaidAccountSubType.Utma:
      return AccountSubType.Utma
    case PlaidAccountSubType.VariableAnnuity:
      return AccountSubType.VariableAnnuity
    case PlaidAccountSubType.CreditCard:
      return AccountSubType.CreditCard
    case PlaidAccountSubType.Paypal:
      return AccountSubType.Paypal
    case PlaidAccountSubType.Cd:
      return AccountSubType.CD
    case PlaidAccountSubType.Checking:
      return AccountSubType.Checking
    case PlaidAccountSubType.Savings:
      return AccountSubType.Savings
    case PlaidAccountSubType.MoneyMarket:
      return AccountSubType.MoneyMarket
    case PlaidAccountSubType.Prepaid:
      return AccountSubType.Prepaid
    case PlaidAccountSubType.Auto:
      return AccountSubType.Auto
    case PlaidAccountSubType.Business:
      return AccountSubType.Business
    case PlaidAccountSubType.Commercial:
      return AccountSubType.Commercial
    case PlaidAccountSubType.Construction:
      return AccountSubType.Construction
    case PlaidAccountSubType.Consumer:
      return AccountSubType.Consumer
    case PlaidAccountSubType.HomeEquity:
      return AccountSubType.HomeEquity
    case PlaidAccountSubType.Loan:
      return AccountSubType.Loan
    case PlaidAccountSubType.Mortgage:
      return AccountSubType.Mortgage
    case PlaidAccountSubType.Overdraft:
      return AccountSubType.Overdraft
    case PlaidAccountSubType.LineOfCredit:
      return AccountSubType.LineOfCredit
    case PlaidAccountSubType.Student:
      return AccountSubType.Student
    case PlaidAccountSubType.CashManagement:
      return AccountSubType.CashManagement
    case PlaidAccountSubType.Keogh:
      return AccountSubType.Keogh
    case PlaidAccountSubType.MutualFund:
      return AccountSubType.MutualFund
    case PlaidAccountSubType.Recurring:
      return AccountSubType.Recurring
    case PlaidAccountSubType.Rewards:
      return AccountSubType.Rewards
    case PlaidAccountSubType.SafeDeposit:
      return AccountSubType.SafeDeposit
    case PlaidAccountSubType.Sarsep:
      return AccountSubType.Sarsep
    case PlaidAccountSubType.Payroll:
      return AccountSubType.Payroll
    default:
      return AccountSubType.Other
  }
}
