import { MigrationInterface, QueryRunner } from "typeorm";

export class RentalIncomeCategory1712952819327 implements MigrationInterface {
    name = 'RentalIncomeCategory1712952819327'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TYPE "public"."category_systemcategory_enum" RENAME TO "category_systemcategory_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."category_systemcategory_enum" AS ENUM('accountTransfer', 'accountingAndFinancialPlanning', 'atmFees', 'automotive', 'beerWineAndLiquor', 'bikesAndScooters', 'bookstoresAndNewsstands', 'carPayment', 'cashAdvancesAndLoans', 'casinosAndGambling', 'childcare', 'clothingAndAccessories', 'coffee', 'consultingAndLegal', 'convenienceStores', 'creditCardPayment', 'dentalCare', 'departmentStores', 'deposit', 'discountStores', 'dividends', 'donations', 'education', 'electronics', 'eyeCare', 'fastFood', 'flights', 'foreignTransactionFees', 'furniture', 'gas', 'gasAndElectricity', 'giftsAndNovelties', 'governmentDepartmentsAndAgencies', 'groceries', 'gymsAndFitnessCenters', 'hairAndBeauty', 'hardware', 'insufficientFunds', 'insurance', 'interestCharge', 'interestEarned', 'internetAndCable', 'investmentAndRetirementFunds', 'laundryAndDryCleaning', 'lodging', 'miscellaneous', 'mortgagePayment', 'musicAndAudio', 'nursingCare', 'officeSupplies', 'onlineMarketplaces', 'otherBankFees', 'otherEntertainment', 'otherFoodAndDrink', 'otherGeneralMerchandise', 'otherGeneralServices', 'otherGovernmentAndNonProfit', 'otherHomeImprovement', 'otherIncome', 'otherMedical', 'otherPayment', 'otherPersonalCare', 'otherTransferIn', 'otherTransferOut', 'otherTransportation', 'otherTravel', 'otherUtilities', 'overdraftFees', 'parking', 'personalLoanPayment', 'petSupplies', 'pharmaciesAndSupplements', 'postageAndShipping', 'primaryCare', 'publicTransit', 'rent', 'rentalCars', 'rentalIncome', 'repairAndMaintenance', 'restaurant', 'retirementPension', 'savings', 'security', 'sewageAndWasteManagement', 'sportingEventsAmusementParksAndMuseums', 'sportingGoods', 'storage', 'studentLoanPayment', 'superstores', 'taxPayment', 'taxRefund', 'taxisAndRideShares', 'telephone', 'tobaccoAndVape', 'tolls', 'tvAndMovies', 'unemployment', 'vendingMachines', 'veterinaryServices', 'videoGames', 'wages', 'water', 'withdrawal')`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "systemCategory" TYPE "public"."category_systemcategory_enum" USING "systemCategory"::"text"::"public"."category_systemcategory_enum"`);
        await queryRunner.query(`DROP TYPE "public"."category_systemcategory_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."category_systemcategory_enum_old" AS ENUM('accountTransfer', 'accountingAndFinancialPlanning', 'atmFees', 'automotive', 'beerWineAndLiquor', 'bikesAndScooters', 'bookstoresAndNewsstands', 'carPayment', 'cashAdvancesAndLoans', 'casinosAndGambling', 'childcare', 'clothingAndAccessories', 'coffee', 'consultingAndLegal', 'convenienceStores', 'creditCardPayment', 'dentalCare', 'departmentStores', 'deposit', 'discountStores', 'dividends', 'donations', 'education', 'electronics', 'eyeCare', 'fastFood', 'flights', 'foreignTransactionFees', 'furniture', 'gas', 'gasAndElectricity', 'giftsAndNovelties', 'governmentDepartmentsAndAgencies', 'groceries', 'gymsAndFitnessCenters', 'hairAndBeauty', 'hardware', 'insufficientFunds', 'insurance', 'interestCharge', 'interestEarned', 'internetAndCable', 'investmentAndRetirementFunds', 'laundryAndDryCleaning', 'lodging', 'miscellaneous', 'mortgagePayment', 'musicAndAudio', 'nursingCare', 'officeSupplies', 'onlineMarketplaces', 'otherBankFees', 'otherEntertainment', 'otherFoodAndDrink', 'otherGeneralMerchandise', 'otherGeneralServices', 'otherGovernmentAndNonProfit', 'otherHomeImprovement', 'otherIncome', 'otherMedical', 'otherPayment', 'otherPersonalCare', 'otherTransferIn', 'otherTransferOut', 'otherTransportation', 'otherTravel', 'otherUtilities', 'overdraftFees', 'parking', 'personalLoanPayment', 'petSupplies', 'pharmaciesAndSupplements', 'postageAndShipping', 'primaryCare', 'publicTransit', 'rent', 'rentalCars', 'repairAndMaintenance', 'restaurant', 'retirementPension', 'savings', 'security', 'sewageAndWasteManagement', 'sportingEventsAmusementParksAndMuseums', 'sportingGoods', 'storage', 'studentLoanPayment', 'superstores', 'taxPayment', 'taxRefund', 'taxisAndRideShares', 'telephone', 'tobaccoAndVape', 'tolls', 'tvAndMovies', 'unemployment', 'vendingMachines', 'veterinaryServices', 'videoGames', 'wages', 'water', 'withdrawal')`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "systemCategory" TYPE "public"."category_systemcategory_enum_old" USING "systemCategory"::"text"::"public"."category_systemcategory_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."category_systemcategory_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."category_systemcategory_enum_old" RENAME TO "category_systemcategory_enum"`);
    }
}
