import { AccountSubType } from 'shared-types'

import { MxAccountSubType } from '../types/mx-account-sub-type'
import { MxAccountType } from '../types/mx-account-type'

export const mapAccountSubType = (accountSubType: MxAccountSubType | null, accountType: MxAccountType) => {
  if (accountSubType == null) {
    switch (accountType) {
      case MxAccountType.Checking:
        return AccountSubType.Checking
      case MxAccountType.Savings:
        return AccountSubType.Savings
      case MxAccountType.Loan:
        return AccountSubType.Loan
      case MxAccountType.CreditCard:
        return AccountSubType.CreditCard
      case MxAccountType.Investment:
        return AccountSubType.Investment
      case MxAccountType.LineOfCredit:
        return AccountSubType.LineOfCredit
      case MxAccountType.Mortgage:
        return AccountSubType.Mortgage
      case MxAccountType.Property:
        return AccountSubType.Property
      case MxAccountType.Cash:
        return AccountSubType.Cash
      case MxAccountType.Insurance:
        return AccountSubType.OtherInsurance
      case MxAccountType.Prepaid:
        return AccountSubType.Prepaid
      case MxAccountType.CheckingLineOfCredit:
        return AccountSubType.LineOfCredit
      default:
        return AccountSubType.Other
    }
  }

  switch (accountSubType) {
    case MxAccountSubType.MoneyMarket:
      return AccountSubType.MoneyMarket
    case MxAccountSubType.CertificateOfDeposit:
      return AccountSubType.CD
    case MxAccountSubType.Auto:
      return AccountSubType.Auto
    case MxAccountSubType.Student:
      return AccountSubType.Student
    case MxAccountSubType.SmallBusiness:
      return AccountSubType.Business
    case MxAccountSubType.Personal:
      return AccountSubType.Loan
    case MxAccountSubType.PersonalWithCollateral:
      return AccountSubType.Loan
    case MxAccountSubType.HomeEquity:
      return AccountSubType.HomeEquity
    case MxAccountSubType.Boat:
      return AccountSubType.Vehicle
    case MxAccountSubType.Powersports:
      return AccountSubType.Vehicle
    case MxAccountSubType.Rv:
      return AccountSubType.Vehicle
    case MxAccountSubType.Heloc:
      return AccountSubType.HomeEquity
    case MxAccountSubType.Plan401K:
      return AccountSubType._401k
    case MxAccountSubType.Plan403B:
      return AccountSubType._403B
    case MxAccountSubType.Plan529:
      return AccountSubType._529
    case MxAccountSubType.Ira:
      return AccountSubType.Ira
    case MxAccountSubType.RolloverIra:
      return AccountSubType.Ira
    case MxAccountSubType.RothIra:
      return AccountSubType.Roth
    case MxAccountSubType.Taxable:
      return AccountSubType.Investment
    case MxAccountSubType.NonTaxable:
      return AccountSubType.NonTaxableBrokerageAccount
    case MxAccountSubType.Brokerage:
      return AccountSubType.Brokerage
    case MxAccountSubType.Trust:
      return AccountSubType.Trust
    case MxAccountSubType.UniformGiftsToMinorsAct:
      return AccountSubType.Ugma
    case MxAccountSubType.Plan457:
      return AccountSubType._457b
    case MxAccountSubType.Pension:
      return AccountSubType.Pension
    case MxAccountSubType.EmployeeStockOwnershipPlan:
      return AccountSubType.StockPlan
    case MxAccountSubType.SimplifiedEmployeePension:
      return AccountSubType.Pension
    case MxAccountSubType.SimpleIra:
      return AccountSubType.SimpleIra
    case MxAccountSubType.PlanRoth401K:
      return AccountSubType.Roth401k
    case MxAccountSubType.FixedAnnuity:
      return AccountSubType.FixedAnnuity
    case MxAccountSubType.VariableAnnuity:
      return AccountSubType.VariableAnnuity
    case MxAccountSubType.Hsa:
      return AccountSubType.Hsa
    case MxAccountSubType.TaxFreeSavingsAccount:
      return AccountSubType.Tfsa
    case MxAccountSubType.Individual:
      return AccountSubType.Investment
    case MxAccountSubType.RegisteredRetirementIncomeFund:
      return AccountSubType.Retirement
    case MxAccountSubType.CashManagementAccount:
      return AccountSubType.CashManagement
    case MxAccountSubType.EmployeeStockPurchasePlan:
      return AccountSubType.StockPlan
    case MxAccountSubType.RegisteredEducationSavingsPlan:
      return AccountSubType.Resp
    case MxAccountSubType.ProfitSharingPlan:
      return AccountSubType.ProfitSharingPlan
    case MxAccountSubType.UniformTransferToMinorsAct:
      return AccountSubType.Utma
    case MxAccountSubType.Plan401A:
      return AccountSubType._401a
    case MxAccountSubType.SarsepIra:
      return AccountSubType.Sarsep
    case MxAccountSubType.FixedAnnuityTraditionalIra:
      return AccountSubType.Ira
    case MxAccountSubType.VariableAnnuityTraditionalIra:
      return AccountSubType.Ira
    case MxAccountSubType.SeppIra:
      return AccountSubType.SepIra
    case MxAccountSubType.InheritedTraditionalIra:
      return AccountSubType.Ira
    case MxAccountSubType.FixedAnnuityRothIra:
      return AccountSubType.Ira
    case MxAccountSubType.VariableAnnuityRothIra:
      return AccountSubType.Ira
    case MxAccountSubType.InheritedRothIra:
      return AccountSubType.Ira
    case MxAccountSubType.Coverdell:
      return AccountSubType.Investment
    case MxAccountSubType.AdvisoryAccount:
      return AccountSubType.Investment
    case MxAccountSubType.BrokerageMargin:
      return AccountSubType.Brokerage
    case MxAccountSubType.CharitableGiftAccount:
      return AccountSubType.Investment
    case MxAccountSubType.ChurchAccount:
      return AccountSubType.Investment
    case MxAccountSubType.Conservatorship:
      return AccountSubType.Investment
    case MxAccountSubType.Custodial:
      return AccountSubType.Investment
    case MxAccountSubType.DefinedBenefitPlan:
      return AccountSubType.Investment
    case MxAccountSubType.DefinedContributionPlan:
      return AccountSubType.Investment
    case MxAccountSubType.Educational:
      return AccountSubType.EducationSavingsAccount
    case MxAccountSubType.Estate:
      return AccountSubType.Investment
    case MxAccountSubType.Executor:
      return AccountSubType.Investment
    case MxAccountSubType.GroupRetirementSavingsPlan:
      return AccountSubType.Retirement
    case MxAccountSubType.GuaranteedInvestmentCertificate:
      return AccountSubType.Gic
    case MxAccountSubType.Hra:
      return AccountSubType.HealthReimbursementArrangement
    case MxAccountSubType.IndexedAnnuity:
      return AccountSubType.OtherAnnuity
    case MxAccountSubType.InvestmentClub:
      return AccountSubType.Investment
    case MxAccountSubType.IrrevocableTrust:
      return AccountSubType.Trust
    case MxAccountSubType.JointTenantsByEntirity:
      return AccountSubType.Investment
    case MxAccountSubType.JointTenantsCommunityProperty:
      return AccountSubType.Investment
    case MxAccountSubType.JointTenantsInCommon:
      return AccountSubType.Investment
    case MxAccountSubType.JointTenantsWithRightsOfSurvivorship:
      return AccountSubType.Investment
    case MxAccountSubType.KeoughPlan:
      return AccountSubType.Keogh
    case MxAccountSubType.LifeIncomeFund:
      return AccountSubType.Investment
    case MxAccountSubType.LivingTrust:
      return AccountSubType.Trust
    case MxAccountSubType.LockedInRetirementAccount:
      return AccountSubType.Retirement
    case MxAccountSubType.LockedInRetirementInvestmentFund:
      return AccountSubType.Retirement
    case MxAccountSubType.LockedInRetirementSavingsAccount:
      return AccountSubType.Retirement
    case MxAccountSubType.MoneyPurchasePlan:
      return AccountSubType.Investment
    case MxAccountSubType.Partnership:
      return AccountSubType.Investment
    case MxAccountSubType.Plan409A:
      return AccountSubType.Investment
    case MxAccountSubType.PlanRoth403B:
      return AccountSubType._403B
    case MxAccountSubType.RegisteredDisabilitySavingsPlan:
      return AccountSubType.Investment
    case MxAccountSubType.RegisteredLockedInSavingsPlan:
      return AccountSubType.Savings
    case MxAccountSubType.RegisteredPensionPlan:
      return AccountSubType.Pension
    case MxAccountSubType.RegisteredRetirementSavingsPlan:
      return AccountSubType.Rrsp
    case MxAccountSubType.RevocableTrust:
      return AccountSubType.Trust
    case MxAccountSubType.RothConversion:
      return AccountSubType.Roth
    case MxAccountSubType.SoleProprietorship:
      return AccountSubType.Investment
    case MxAccountSubType.SpousalIra:
      return AccountSubType.Ira
    case MxAccountSubType.SpousalRothIra:
      return AccountSubType.Ira
    case MxAccountSubType.TestamentaryTrust:
      return AccountSubType.Trust
    case MxAccountSubType.ThriftSavingsPlan:
      return AccountSubType.ThriftSavingsPlan
    case MxAccountSubType.InheritedAnnuity:
      return AccountSubType.OtherAnnuity
    case MxAccountSubType.CorporateAccount:
      return AccountSubType.Investment
    case MxAccountSubType.LimitedLiabilityAccount:
      return AccountSubType.Investment
    case MxAccountSubType.VehicleInsurance:
      return AccountSubType.OtherInsurance
    case MxAccountSubType.Disability:
      return AccountSubType.OtherInsurance
    case MxAccountSubType.Health:
      return AccountSubType.OtherInsurance
    case MxAccountSubType.LongTermCare:
      return AccountSubType.OtherInsurance
    case MxAccountSubType.PropertyAndCasualty:
      return AccountSubType.OtherInsurance
    case MxAccountSubType.UniversalLife:
      return AccountSubType.LifeInsurance
    case MxAccountSubType.TermLife:
      return AccountSubType.LifeInsurance
    case MxAccountSubType.WholeLife:
      return AccountSubType.LifeInsurance
    case MxAccountSubType.AccidentalDeathAndDismemberment:
      return AccountSubType.LifeInsurance
    case MxAccountSubType.VariableUniversalLife:
      return AccountSubType.LifeInsurance
    default:
      return AccountSubType.Other
  }
}
