import { SystemCategory } from 'shared-types'

import { MxCategory } from '../types/mx-category'

export const mapCategory = (category: MxCategory) => {
  switch (category) {
    case MxCategory.ATMFee:
      return SystemCategory.AtmFees
    case MxCategory.Advertising:
      return SystemCategory.OtherGeneralServices
    case MxCategory.AirTravel:
      return SystemCategory.Flights
    case MxCategory.AlcoholAndBars:
      return SystemCategory.BeerWineAndLiquor
    case MxCategory.Allowance:
      return SystemCategory.AtmFees
    case MxCategory.Amusement:
      return SystemCategory.SportingEventsAmusementParksAndMuseums
    case MxCategory.Arts:
      return SystemCategory.OtherGeneralMerchandise
    case MxCategory.AutoAndTransport:
      return SystemCategory.Automotive
    case MxCategory.AutoInsurance:
      return SystemCategory.Insurance
    case MxCategory.AutoPayment:
      return SystemCategory.CarPayment
    case MxCategory.BabySupplies:
      return SystemCategory.Childcare
    case MxCategory.BabysitterAndDaycare:
      return SystemCategory.Childcare
    case MxCategory.BankingFee:
      return SystemCategory.OtherBankFees
    case MxCategory.BillsAndUtilities:
      return SystemCategory.OtherUtilities
    case MxCategory.Bonus:
      return SystemCategory.OtherIncome
    case MxCategory.Books:
      return SystemCategory.BookstoresAndNewsstands
    case MxCategory.BooksAndSupplies:
      return SystemCategory.BookstoresAndNewsstands
    case MxCategory.BusinessServices:
      return SystemCategory.OtherGeneralServices
    case MxCategory.Buy:
      return SystemCategory.Miscellaneous
    case MxCategory.Cash:
      return SystemCategory.CashAdvancesAndLoans
    case MxCategory.Charity:
      return SystemCategory.Donations
    case MxCategory.Check:
      return SystemCategory.Deposit
    case MxCategory.ChildSupport:
      return SystemCategory.Childcare
    case MxCategory.Clothing:
      return SystemCategory.ClothingAndAccessories
    case MxCategory.CoffeeShops:
      return SystemCategory.Coffee
    case MxCategory.CreditCardPayment:
      return SystemCategory.CreditCardPayment
    case MxCategory.Dentist:
      return SystemCategory.DentalCare
    case MxCategory.Deposit:
      return SystemCategory.Deposit
    case MxCategory.DividendAndCapGains:
      return SystemCategory.Dividends
    case MxCategory.Doctor:
      return SystemCategory.OtherMedical
    case MxCategory.DomainNames:
      return SystemCategory.OtherGeneralServices
    case MxCategory.Education:
      return SystemCategory.Education
    case MxCategory.ElectronicsAndSoftware:
      return SystemCategory.Electronics
    case MxCategory.Entertainment:
      return SystemCategory.OtherEntertainment
    case MxCategory.Eyecare:
      return SystemCategory.EyeCare
    case MxCategory.FastFood:
      return SystemCategory.FastFood
    case MxCategory.FederalTax:
      return SystemCategory.TaxPayment
    case MxCategory.FeesAndCharges:
      return SystemCategory.OtherBankFees
    case MxCategory.FinanceCharge:
      return SystemCategory.InterestCharge
    case MxCategory.Financial:
      return SystemCategory.AccountingAndFinancialPlanning
    case MxCategory.FinancialAdvisor:
      return SystemCategory.AccountingAndFinancialPlanning
    case MxCategory.FoodAndDining:
      return SystemCategory.Restaurant
    case MxCategory.FraudProtection:
      return SystemCategory.OtherGeneralServices
    case MxCategory.Furnishings:
      return SystemCategory.Furniture
    case MxCategory.Gas:
      return SystemCategory.Gas
    case MxCategory.Gift:
      return SystemCategory.GiftsAndNovelties
    case MxCategory.GiftsAndDonations:
      return SystemCategory.GiftsAndNovelties
    case MxCategory.Groceries:
      return SystemCategory.Groceries
    case MxCategory.Gym:
      return SystemCategory.GymsAndFitnessCenters
    case MxCategory.Hair:
      return SystemCategory.HairAndBeauty
    case MxCategory.HealthAndFitness:
      return SystemCategory.GymsAndFitnessCenters
    case MxCategory.HealthInsurance:
      return SystemCategory.Insurance
    case MxCategory.Hobbies:
      return SystemCategory.OtherEntertainment
    case MxCategory.Home:
      return SystemCategory.OtherHomeImprovement
    case MxCategory.HomeImprovement:
      return SystemCategory.OtherHomeImprovement
    case MxCategory.HomeInsurance:
      return SystemCategory.Insurance
    case MxCategory.HomePhone:
      return SystemCategory.Telephone
    case MxCategory.HomeServices:
      return SystemCategory.OtherHomeImprovement
    case MxCategory.HomeSupplies:
      return SystemCategory.OfficeSupplies
    case MxCategory.Hosting:
      return SystemCategory.OtherGeneralServices
    case MxCategory.Hotel:
      return SystemCategory.Lodging
    case MxCategory.Income:
      return SystemCategory.Wages
    case MxCategory.InterestIncome:
      return SystemCategory.InterestEarned
    case MxCategory.Internet:
      return SystemCategory.InternetAndCable
    case MxCategory.Investments:
      return SystemCategory.Dividends
    case MxCategory.Kids:
      return SystemCategory.Childcare
    case MxCategory.KidsActivities:
      return SystemCategory.Childcare
    case MxCategory.LateFee:
      return SystemCategory.OtherBankFees
    case MxCategory.Laundry:
      return SystemCategory.LaundryAndDryCleaning
    case MxCategory.LawnAndGarden:
      return SystemCategory.OtherHomeImprovement
    case MxCategory.Legal:
      return SystemCategory.ConsultingAndLegal
    case MxCategory.LifeInsurance:
      return SystemCategory.Insurance
    case MxCategory.LocalTax:
      return SystemCategory.TaxPayment
    case MxCategory.MobilePhone:
      return SystemCategory.Telephone
    case MxCategory.MortgageAndRent:
      return SystemCategory.Rent
    case MxCategory.MortgagePayment:
      return SystemCategory.MortgagePayment
    case MxCategory.MoviesAndDVDs:
      return SystemCategory.TvAndMovies
    case MxCategory.Music:
      return SystemCategory.MusicAndAudio
    case MxCategory.NewspapersAndMagazines:
      return SystemCategory.BookstoresAndNewsstands
    case MxCategory.OfficeSupplies:
      return SystemCategory.OfficeSupplies
    case MxCategory.Parking:
      return SystemCategory.Parking
    case MxCategory.Paycheck:
      return SystemCategory.Wages
    case MxCategory.PersonalCare:
      return SystemCategory.OtherPersonalCare
    case MxCategory.PetFoodAndSupplies:
      return SystemCategory.PetSupplies
    case MxCategory.PetGrooming:
      return SystemCategory.VeterinaryServices
    case MxCategory.Pets:
      return SystemCategory.VeterinaryServices
    case MxCategory.Pharmacy:
      return SystemCategory.PharmaciesAndSupplements
    case MxCategory.Printing:
      return SystemCategory.OtherGeneralServices
    case MxCategory.PropertyTax:
      return SystemCategory.TaxPayment
    case MxCategory.PublicTransportation:
      return SystemCategory.PublicTransit
    case MxCategory.Reimbursement:
      return SystemCategory.OtherIncome
    case MxCategory.RentalCarAndTaxi:
      return SystemCategory.TaxisAndRideShares
    case MxCategory.RentalIncome:
      return SystemCategory.OtherIncome
    case MxCategory.Restaurants:
      return SystemCategory.Restaurant
    case MxCategory.ReturnedPurchase:
      return SystemCategory.OtherIncome
    case MxCategory.SalesTax:
      return SystemCategory.TaxPayment
    case MxCategory.Sell:
      return SystemCategory.InvestmentAndRetirementFunds
    case MxCategory.ServiceAndParts:
      return SystemCategory.Automotive
    case MxCategory.ServiceFee:
      return SystemCategory.AtmFees
    case MxCategory.Shipping:
      return SystemCategory.PostageAndShipping
    case MxCategory.Shopping:
      return SystemCategory.OtherGeneralMerchandise
    case MxCategory.SpaAndMassage:
      return SystemCategory.OtherMedical
    case MxCategory.SportingGoods:
      return SystemCategory.SportingGoods
    case MxCategory.Sports:
      return SystemCategory.SportingGoods
    case MxCategory.StateTax:
      return SystemCategory.TaxPayment
    case MxCategory.StudentLoan:
      return SystemCategory.StudentLoanPayment
    case MxCategory.Taxes:
      return SystemCategory.TaxPayment
    case MxCategory.Television:
      return SystemCategory.TvAndMovies
    case MxCategory.Toys:
      return SystemCategory.Childcare
    case MxCategory.TradeCommissions:
      return SystemCategory.OtherIncome
    case MxCategory.Transfer:
      return SystemCategory.OtherTransferOut
    case MxCategory.TransferforCashSpending:
      return SystemCategory.CashAdvancesAndLoans
    case MxCategory.Travel:
      return SystemCategory.OtherTravel
    case MxCategory.Tuition:
      return SystemCategory.Education
    case MxCategory.Uncategorized:
      return SystemCategory.Miscellaneous
    case MxCategory.Utilities:
      return SystemCategory.OtherUtilities
    case MxCategory.Vacation:
      return SystemCategory.OtherTravel
    case MxCategory.Veterinary:
      return SystemCategory.VeterinaryServices
    case MxCategory.Withdrawal:
      return SystemCategory.Withdrawal
    default:
      return SystemCategory.Miscellaneous
  }
}
